server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://10.80.43.196:3306/forum
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: forum
    password: rememberus1nthed@yofend


#logging:
#  level:
#    org.tongji.programming.mapper: debug

forum:
  search-engine:
    post: post


