server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://10.80.43.196:3306/forum_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: forum
    password: rememberus1nthed@yofend
  data:
    redis:
      host: 10.80.42.189
      password: rememberus
      database: 13


#logging:
#  level:
#    org.tongji.programming.mapper: debug

forum:
  search-engine:
    post: post_dev


