server:
  port: 9001
spring:
  data:
    redis:
      host: 10.80.42.189
      password: rememberus
      database: 12
  datasource:
    url: jdbc:mysql://10.80.43.196:3306/forum_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: forum
    password: rememberus1nthed@yofend

#logging:
#  level:
#    org.tongji.programming.mapper: debug

forum:
  forum:
    cos-secret-id: AKIDOemkY7XltqjAZxAB9zgDdwJct5DJRYdl
    cos-secret-key: OhqdMxW1NdmomdNzX3NZfhYI9vdEev22
    cos-region: ap-shanghai
    cos-bucket: forum-1305284863
    cos-prefix: user-upload/
    cos-result-baseurl: https://forum-1305284863.cos.ap-shanghai.myqcloud.com/
  user:
    default-avatar: https://forum-1305284863.cos.ap-shanghai.myqcloud.com/user-default.png

