server:
  port: 9001
spring:
  data:
    redis:
      host: 10.80.42.189
      password: rememberus
      database: 12
  datasource:
    url: jdbc:mysql://10.80.43.196:3306/forum_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: forum
    password: rememberus1nthed@yofend
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


#logging:
#  level:
#    org.tongji.programming.mapper: debug

forum:
  s3:
    endpoint: http://10.80.43.196:9000/
    bucket: forum
    accessKey: 50My98IAnFXDniBxbmFK
    secretKey: qLfkBObNiIzHOStJzmiSLd6KwTiYnY8qBlOR0T9r
    baseUrl: http://10.80.43.196/s3/forum
    prefix:
      upload: /user-upload/
      avatar: /user-avatar/
      cardBg: /user-card/
  user:
    default-avatar: http://10.80.43.196/s3/forum/user-default.png
  level:
    ta: 1
    admin: 5
    super: 9
  meili:
    host: http://10.80.42.189:7700
    key: keI4qhrWElK6UqFt928AkKjDfIn1skn5cXcqP5sLaHo
  search-engine:
    post: post_dev


